server:
  port: 8080

auth-service:
  base-url: http://internal-auth-service-elb-tf-1420328170.ap-northeast-2.elb.amazonaws.com
role-service:
  base-url: http://internal-role-service-elb-tf-1312481601.ap-northeast-2.elb.amazonaws.com
carbon-emmision-service:
  base-url: http://internal-carbon-emmision-service-elb-tf-1812481603.ap-northeast-2.elb.amazonaws.com